name: 语法错误报告
description: 为文档中的翻译报告语法错误。
labels: [ 语法错误 ]
body:
  - type: markdown
    attributes:
      value: |
        如果您发现文档中任何已有的中文翻译出现**不准确、出现语法错误、错别字**等情况，  
        请您在这里报告翻译错误。  
  - type: dropdown
    id: report
    attributes:
      label: 报告文档
      description: 哪个文档中的中文翻译描述不准确或出现语法错误？
      options:
        - LibrePremium
        - Paper
    validations:
      required: true
  - type: textarea
    id: line
    attributes:
      label: 链接
      description: 请提供出现语法错误的链接，或GitHub存储库对应Markdown页面的链接。
      value: |
        例如：https://docs.poikcue.com/#/PaperMC/Administration/how-to/updating
        或者：https://github.com/poikcue/docs/blob/main/PaperMC/Administration/how-to/updating.md
        以上两个链接都行，提供一个即可。
    validations:
      required: true
  - type: textarea
    id: area
    attributes:
      label: 语法错误所在句
      description: 请复制出现语法错误的句子。
      value: |
        例如：在更新服务器时一并将服务器备份是个好主意
    validations:
      required: true
  - type: input
    id: error
    attributes:
      label: 语法错误文本
      description: 请复制语法错误文本。
      value: |
        例如：是个
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: 建议文本
      description: 您建议修改为什么？您也可以提供您的修改意见，或是这句话出现了什么问题。
      value: |
        例如：将 “是个” 修改为 “是一个”
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 补充
      description: 可选。您有什么想要补充的吗？
    validations:
      required: false
  - type: markdown
    id: thanks
    attributes:
      value: "谢谢！我们会很快注意到您的报告并查看相应文本。"
